### ISSUE TITLE
Meeting minutes

### ISSUE THREAD

**Issue by setriplette** [setriplette/golden_age#3]
Meeting Friday Sept 30 11:20
# Tasks done
- site name
  @ebeshero @RJP43 
  lope.newtfire.org
- added plain text files of Pilgrim of Castile, La moza de cántaro, and La dama boba to repository
  # Tasks for next time
- [ ] Document analysis and beginning regex for La moza de cántaro @msb81 
- [ ] Document analysis and beginning regex for Pilgrim of Castile @ahunker 
- [ ] Document analysis and beginning regex for La dama boba @setriplette
  # Next meeting tasks, tentative date Fri Oct 7 after class
- discuss fuller thesis
- more complete regex

**Comment by setriplette** [comment]
Structural markup for plays

Line in `<l></l>`
Speakers in `<speaker></speaker>`
Speeches (speakers + lines) `<sp></sp>` (goes around stage direction too)
Stage directions in `<stage></stage>`
Act in `<div type="act" number="xsd:int">`
Scene in `<div type="scene" number="xsd:int">`

Remove the pseudo markup and code those things in TEI
